FORMAT: 1A
HOST: http://developer.oneboxtickets.com/dynamic-pricing-api/index.html

# onebox-dynamic-pricing-api

API to share CRM data to our integrated clients.

To do so, we have used a **API Blueprint** standard, **apiary** as an online editing and mocking tool, **aglio** to document it and **getsandbox** as a sandbox provider:
+ [API Blueprint](https://apiblueprint.org/)
+ [apiary.io](http://docs.oneboxdynamicpricingapi.apiary.io/)
+ [getsandbox.com](http://onebox-dynamic-pricing-api.getsandbox.com/)
+ [aglio](https://github.com/danielgtaylor/aglio)
+ [github](https://github.com/joliva-ob/onebox-dynamic-pricing-api)
+ [onebox-developer](http://developer.oneboxtickets.com/dynamic-pricing-api/)

## OAuth2 Requests [/oauth/token]

### Oauth2 Request Access Token [POST]

You will need to use OAuth to access the API.  Write to us at api-support@oneboxtm.com.  We will give you a client ID and client secret. Use this as shown in the following call in order to retrieve a token.
Once you have a token you can use it in all API calls as shown below.

+ Request (application/json)

        {
            "grant_type": "password",
            "client_id": [CLIENT_ID],
            "client_secret": [CLIENT_SECRET],
            "password": [YOURPASSWORD],
            "username": [YOURUSERNAME]
        }

+ Response 201

        {
            "access_token": "[OAUTH2_TOKEN]",
            "token_type":"bearer",
            "expires_in":7200,
            "refresh_token": "[REFRESH_TOKEN]"
        }

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }

## Sales Collection [/dynamic-pricing-api/1.0/sales{?event_id,start_date,end_date,page}]
List all the key data from the sales. It is also allowed filtering between dates and paging.

See below the description of the response fields we consider that need to be explained:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| version                          | (Text) Version of the API               |
| href                             | (Text) Url of the API doc               |
| trace_id                         | (Text) unique identifier of the request |
| parameters                       | (Object) Request filtering used         |

### List All Sales [GET]

Collection of sales, where each sale can have got several different products (ticket items).

+ Request

  + Headers

            Authorization: Bearer [OAUTH2_TOKEN]
            Accept: application/vnd.collection+json

+ Parameters
    + event_id (optional, string) ... Filter by given event id
    + start_date (optional, date) ... Filter by starting date ('2015-08-05T08:40:51.620Z')
    + end_date (optional, date) ... Filter by final date
    + page (optional, number) ... Paginate response to the given page number

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/dynamic-pricing-api/1.0/sales/",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "request_date": "2015-08-05T08:40:51.620Z",
            "parameters":
            {
              "event_id": "",
              "start_date": "",
              "end_date": "",
              "page": 2
            },
            "sales": [
              {
                "id": "JFSKF34K2K4",
                "event_id": "432",
                "event_date": "2015-08-05",
                "event_name": "Campeonato liga LFP 15-16",
                "transaction_date": "2015-08-05T08:40:51.620Z",
                "transaction_type": "SALE",
                "buyer_type_code": "INTEGRATION",
                "products_number": 2,
                "channel_id": "int_channel@oneboxtm.com",
                "products": [
                  {
                      "id": "432k23",
                      "session_id": "12",
                      "session_date": "2015-08-05T08:40:51.620Z",
                      "session_name": "Liga Barcelona - Madrid",
                      "venue_id": "2",
                      "venue_name": "Camp Nou",
                      "price_id": "21",
                      "price_zone_id": "454",
                      "price": 23.3,
                      "section": "tribuna alta B",
                      "seat": "10",
                      "row": "8"
                  },
                  {
                      "id": "432k24",
                      "session_id": "12",
                      "session_date": "2015-08-05T08:40:51.620Z",
                      "session_name": "Liga Barcelona - Madrid",
                      "venue_id": "2",
                      "venue_name": "Camp Nou",
                      "price_id": "22",
                      "price_zone_id": "454",
                      "price": 50.0,
                      "section": "tribuna alta B",
                      "seat": "10",
                      "row": "7"
                  }
                ],
                "links":[
                  {
                    "name": "summary",
                    "prompt": "Summary",
                    "rel": "summary",
                    "href": "summaries?event_id=432",
                    "render": "link"
                  }
                ]
              }
            ],
            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "sales?page=3",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Back",
                "rel": "back",
                "href": "sales?page=1",
                "render": "link"
              }
            ]

          }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }

## Prices Collection [/dynamic-pricing-api/1.0/prices{?start_date,end_date,page}]
List all the key data from the prices. It is also allowed to filtering between dates and paging and by a given price id.

See below the description of the response fields we consider that need to be explained:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| version                          | (Text) Version of the API               |
| href                             | (Text) Url of the API doc               |
| trace_id                         | (Text) unique identifier of the request |
| parameters                       | (Object) Request filtering used         |

### List All Prices [GET]

+ Request

  + Headers

            Authorization: Bearer [OAUTH2_TOKEN]
            Accept: application/vnd.collection+json

+ Parameters

    + start_date (optional, date) ... Filter by starting date (`2015-08-05T08:40:51.620Z`)
    + end_date (optional, date) ... Filter by final date
    + page (optional, number) ... Paginate response to the given page number

+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/dynamic-pricing-api/1.0/prices",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "request_date": "2015-08-05T08:40:51.620Z",
            "parameters":
            {
              "id": "",
              "start_date": "",
              "end_date": "",
              "page": 2
            },
            "prices": [
              {
                "id": "44",
                "price": 23.3,
                "price_zone_id": "454",
                "price_zone_name": "Main grandstand low",
                "event_id": "432",
                "event_date": "2015-08-05",
                "session_id": "12",
                "session_date": "2015-08-05T08:40:51.620Z",
                "venue_id": "2",
                "venue_name": "FCB Camp Nou",
                "buyer_type_code": "INTEGRATION",
                "fee": 2.0,
                "tax": 21.0,
                "external_price_id": ""
              },
              {
                "id": "322",
                "price": 50.0,
                "price_zone_id": "455",
                "price_zone_name": "Main grandstand upper",
                "event_id": "432",
                "event_date": "2015-08-05",
                "session_id": "12",
                "session_date": "2015-08-05T08:40:51.620Z",
                "venue_name": "FCB Camp Nou",
                "venue_id": "2",
                "buyer_type_code": "INTEGRATION",
                "fee": 2.0,
                "tax": 21.0,
                "external_price_id": ""
              }
            ],
            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "prices?page=3",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Back",
                "rel": "back",
                "href": "prices?page=1",
                "render": "link"
              }
            ]

          }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }

## Price Operations [/dynamic-pricing-api/1.0/prices/{id}]
Modification (PUT) and partial modification  (PATCH) are both of them allowed. Notice that PUT is the correct and safe way to perform the modification as PATCH is neither safe nor idempotent.

### Partial modification of a Price [PATCH]

+ Parameters

    + id (required, string) ... Update a given price id

+ Request

      + Headers

            Authorization: Bearer [OAUTH2_TOKEN]
            Accept: application/vnd.collection+json

      + Body

            {
              "id": "44",
              "price": 23.3
            }

+ Response 200 (application/json)

        {
          "id": "44",
          "price": 23.3,
          "price_zone_id": "454",
          "event_id": "432",
          "event_date": "2015-08-05",
          "session_id": "12",
          "session_date": "2015-08-05T08:40:51.620Z",
          "venue_id": "2",
          "buyer_type_code": "INTEGRATION",
          "fee": 2.0,
          "tax": 21.0,
          "external_price_id": ""
        }

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }

### Upate the whole Price [PUT]

+ Parameters

    + id (required, string) ... Update a given price id

+ Request

      + Headers

                Authorization: Bearer [OAUTH2_TOKEN]
                Accept: application/vnd.collection+json

      + Body

            {
              "id": "44",
              "price": 23.3,
              "price_zone_id": "454",
              "event_id": "432",
              "event_date": "2015-08-05",
              "session_id": "12",
              "session_date": "2015-08-05T08:40:51.620Z",
              "venue_id": "2",
              "buyer_type_code": "INTEGRATION",
              "fee": 2.0,
              "tax": 21.0,
              "external_price_id": ""
            }

+ Response 200 (application/json)

          {
            "id": "44",
            "price": 23.3,
            "price_zone_id": "454",
            "event_id": "432",
            "event_date": "2015-08-05",
            "session_id": "12",
            "session_date": "2015-08-05T08:40:51.620Z",
            "venue_id": "2",
            "buyer_type_code": "INTEGRATION",
            "fee": 2.0,
            "tax": 21.0,
            "external_price_id": ""
          }

+ Response 400 (application/json)

          {
            "error": "Bad request",
            "error_description": "There was a syntax error, check your params request and try it again."
          }

+ Response 401 (application/json)

          {
            "error": "unauthorized",
            "error_description": "Full authentication is required to access this resource"
          }

## Summaries Collection [/dynamic-pricing-api/1.0/summaries{?event_id}]
List the summarization data from a given event.

See below the description of the response fields we consider that need to be explained:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| version                          | (Text) Version of the API               |
| href                             | (Text) Url of the API doc               |
| trace_id                         | (Text) unique identifier of the request |
| parameters                       | (Object) Request filtering used         |

### List All Summaries [GET]

+ Request

  + Headers

            Authorization: Bearer [OAUTH2_TOKEN]
            Accept: application/vnd.collection+json

+ Parameters
    + event_id (required, string) ... Filter by given event id.

+ Response 200 (application/json)

         {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/dynamic-pricing-api/1.0/summaries?event_id=23",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "request_date": "2015-08-05T08:40:51.620Z",
            "parameters":
            {
              "event_id": 2
            },
            "summaries": [
              {
                "event_id": "432",
                "event_date": "2015-08-05",
                "event_name": "Campeonato liga LFP 15-16",
                "session_id": "12",
                "venue_id": "2",
                "venue_name": "Camp Nou",
                "total_sold_tickets": 2340,
                "total_onsale_tickets": 3000,
                "available_onesale_tickets": 660,
                "prices_zones":[
                  {
                    "id": "454",
                    "name": "Main grandstand low",
                    "total_sold_tickets": 40,
                    "total_onsale_tickets": 100,
                    "available_onesale_tickets": 60
                  },
                  {
                    "id": "455",
                    "name": "Main grandstand high",
                    "total_sold_tickets": 40,
                    "total_onsale_tickets": 100,
                    "available_onesale_tickets": 60
                  }
                ]
              }
            ],
            "links": []
          }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

         {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
         }

+ Response 401 (application/json)

         {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
         }
